preserve changelog, verify release branch unchanged, minor cleanup
Signed-off-by: Jericho Tolentino <68654047+jericht@users.noreply.github.com>

diff --git a/.github/workflows/release_publish.yml b/.github/workflows/release_publish.yml
--- a/.github/workflows/release_publish.yml
+++ b/.github/workflows/release_publish.yml
@@ -22,10 +22,13 @@ jobs:
 
       - name: VerifyAuthor
         run: |
+          EXPECTED_AUTHOR="client-software-ci@amazon.com"
           AUTHOR=$(git show -s --format='%ae' HEAD)
-          if [[ $AUTHOR != "client-software-ci@amazon.com" ]]; then
-            echo "ERROR: Expected author email to be 'client-software-ci@amazon.com', but got '$AUTHOR'. Aborting release."
+          if [[ $AUTHOR != $EXPECTED_AUTHOR ]]; then
+            echo "ERROR: Expected author email to be '$EXPECTED_AUTHOR', but got '$AUTHOR'. Aborting release."
             exit 1
+          else
+            echo "Verified author email ($AUTHOR) is as expected ($EXPECTED_AUTHOR)"
           fi
 
   Release:
@@ -39,6 +42,16 @@ jobs:
         with:
           ref: release
           fetch-depth: 0
+
+      - name: VerifyReleaseBranch
+        run: |
+          RELEASE_HEAD=$(git show -s --format='%H')
+          if [[ $RELEASE_HEAD != ${{ github.sha }} ]]; then
+            echo "ERROR: tip of release branch ($RELEASE_HEAD) does not match the commit that started this release (${{ github.sha }}). Aborting release."
+            exit 1
+          else
+            echo "Verified tip of release branch ($RELEASE_HEAD) matches the commit that started this release (${{ github.sha }})"
+          fi
 
       - name: Set up Python
         uses: actions/setup-python@v5
@@ -169,5 +182,5 @@ jobs:
       - name: Run CodeBuild
         uses: aws-actions/aws-codebuild-run-build@v1
         with:
-          project-name: openjd-sessions-for-python-Publish
+          project-name: ${{ github.event.repository.name }}-Publish
           hide-cloudwatch-logs: true
